// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: article.sql

package store

import (
	"context"
	"database/sql"
)

const countArticles = `-- name: CountArticles :one
SELECT count(*) FROM articles
`

func (q *Queries) CountArticles(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countArticles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (title, slug, body, published)
VALUES ($1, $2, $3, $4)
RETURNING id, title, slug, body, author_id, published, created_at, updated_at
`

type CreateArticleParams struct {
	Title     string
	Slug      string
	Body      string
	Published bool
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, createArticle,
		arg.Title,
		arg.Slug,
		arg.Body,
		arg.Published,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Body,
		&i.AuthorID,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :execrows
DELETE FROM articles WHERE id = $1
`

func (q *Queries) DeleteArticle(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteArticle, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getArticle = `-- name: GetArticle :one
SELECT id, title, slug, body, author_id, published, created_at, updated_at FROM articles WHERE id = $1
`

func (q *Queries) GetArticle(ctx context.Context, id string) (Article, error) {
	row := q.db.QueryRowContext(ctx, getArticle, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Body,
		&i.AuthorID,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArticleBySlug = `-- name: GetArticleBySlug :one
SELECT id, title, slug, body, author_id, published, created_at, updated_at FROM articles WHERE slug = $1
`

func (q *Queries) GetArticleBySlug(ctx context.Context, slug string) (Article, error) {
	row := q.db.QueryRowContext(ctx, getArticleBySlug, slug)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Body,
		&i.AuthorID,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArticles = `-- name: ListArticles :many
SELECT id, title, slug, body, author_id, published, created_at, updated_at FROM articles
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $1
`

type ListArticlesParams struct {
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListArticles(ctx context.Context, arg ListArticlesParams) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, listArticles, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Article{}
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Body,
			&i.AuthorID,
			&i.Published,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE articles
SET title      = COALESCE($1, title),
    slug       = COALESCE($2, slug),
    body       = COALESCE($3, body),
    published  = COALESCE($4, published),
    updated_at = now()
WHERE id = $5
RETURNING id, title, slug, body, author_id, published, created_at, updated_at
`

type UpdateArticleParams struct {
	Title     sql.NullString
	Slug      sql.NullString
	Body      *string
	Published sql.NullBool
	ID        string
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, updateArticle,
		arg.Title,
		arg.Slug,
		arg.Body,
		arg.Published,
		arg.ID,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Body,
		&i.AuthorID,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
