// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
	"encoding/json"
)

type Article struct {
	ID        string
	Title     string
	Slug      string
	Body      string
	AuthorID  string
	Published bool
	CreatedAt int64
	UpdatedAt int64
}

type CacheItem struct {
	Key       string
	Value     json.RawMessage
	ExpiresAt sql.NullTime
}

type User struct {
	ID          string
	Username    string
	PhoneNo     string
	AvatarUrl   *string
	IsBanned    sql.NullBool
	Verified    bool
	CreatedAt   int64
	UpdatedAt   int64
	LastLoginAt sql.NullInt64
}
