// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CountArticles(ctx context.Context) (int64, error)
	CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error)
	DeleteArticle(ctx context.Context, id string) (int64, error)
	GetArticle(ctx context.Context, id string) (Article, error)
	GetArticleBySlug(ctx context.Context, slug string) (Article, error)
	ListArticles(ctx context.Context, arg ListArticlesParams) ([]Article, error)
	UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error)
}

var _ Querier = (*Queries)(nil)
